### ISSUE TITLE
Could not deserialize key data

### ISSUE THREAD

**Issue by alsiPanda** [elishowk/django-webpush-demo#5]
Hi @elishowk, I am using your project's javascript code, with some modifications (my front end is flutter web), and the django-push-notification plugin by jazzband. After solving all kinds of errors, I am stuck at this error `ValueError: Could not deserialize key data`. This happens when executing device.send_message(message).
My flutter web front end is running on localhost and django rest backend in google compute engine without any SSL or domain name. 
I wanted to confirm with you if lack of SSL is the issue ?

**Comment by kitlu007** [comment]
I'm facing the same issue. Couldny fix it yet.

**Comment by elishowk** [comment]
Hi, 

This demo code is not maintained unfortunately, if you share more details and where the error happens, then we could try to figure something out
But yes, you need HTTPS for Service workers to communicate properly with the Browser's vendor Notification servers, see the README @ Deployment https://github.com/elishowk/django-webpush-demo#deployment

Cheers

Dim 13 déc 2020, à 04:51, kitlu007 a écrit :
